services:
  app:
    build: .
    volumes:
      - .env:/var/www/html/.env
      - ./:/var/www/packages/ICEPAY
    ports:
      - 8011:80
  db:
    image: mariadb:latest
    ports:
      - 3011:3306
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    environment:
      PMA_HOST: db
      PMA_USER: ${DB_USERNAME}
      PMA_PASSWORD: ${DB_PASSWORD}
    ports:
      - 8019:80
    platform: linux/amd64
